version: '3.8'
services:
  postgres:
    image: postgres:latest
    container_name: crm-db
    restart: always
    environment:
      POSTGRES_USER: crm_user
      POSTGRES_PASSWORD: crm_pass
      POSTGRES_DB: crm_database
    ports:
      - "5432:5432"

  rabbitmq:
    image: rabbitmq:3-management
    container_name: crm-rabbitmq
    restart: always
    ports:
      - "5672:5672"
      - "15672:15672"

  kafka:
    image: bitnami/kafka:latest
    container_name: crm-kafka
    restart: always
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092
    ports:
      - "9092:9092"

  zookeeper:
    image: bitnami/zookeeper:latest
    container_name: crm-zookeeper
    restart: always
    ports:
      - "2181:2181"
